homepage
MostafaBarodi/web-portfolio pull request #1
Opened 2023-05-03 12:59 UTC by MostafaBarodi

this is a demo for the home page of my personal portfolio using a Figo template

2023-05-03 13:02 UTC, iambenkis reviewed
Hi @MostafaBarodi  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that has linters that do not pass, make sure you solve them and the ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-04 13:53 UTC, DuaneDave requested changes
Hi @MostafaBarodi  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Correct application of the choice font
✔️ Correct workflow used


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 13:53 UTC, DuaneDave commented on index.html
> +        <nav id="nav">
To be semantically correct, I recommend that you remove this nav tag since there is already a nav existing inside the header tag.

<img width="217" alt="body" src="https://user-images.githubusercontent.com/84930355/236227023-39353c3f-ade4-4013-9c3c-dd20269794b2.PNG">


I added a blue tick on the sides of the screenshot.

2023-05-04 13:53 UTC, DuaneDave commented on index.html
> +                 </ul>
This is still part of the headline section hence; the footer tag shouldn't be used here to be semantically correct.

2023-05-04 13:53 UTC, DuaneDave commented on index.html
> +        </nav>
To be consistent with the template, I recommend removing the excess white space above the navigation and also to use the correct font size and font weight for the logo.

<img width="221" alt="nav" src="https://user-images.githubusercontent.com/84930355/236225169-b852fec0-2c57-4a72-acc5-37dcb9e2b78b.PNG">

2023-05-04 13:53 UTC, DuaneDave commented on index.html
> +<body>
There is a default margin of 8px on the body and it is adding some inconsistency in your design with respect to the template. To mitigate this, I recommend adding `margin: 0` to the body in your CSS.

2023-05-04 17:21 UTC, osamaashraf6 requested changes
Hi @MostafaBarodi 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![SoCloseAlmostGIF (4)](https://user-images.githubusercontent.com/83360636/236280842-c064acec-7282-47a6-bc1e-bfaef1e6254c.gif)


## Highlights🎉🎉

- [x] Not linter errors present🚀
- [x] Good descriptive pull request👌
- [x] Follow the GitHub flow 💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 17:21 UTC, osamaashraf6 commented on index.html
> +        </nav>
- [ ] While you make a great effort 😃 at the project I see that you removed the open tag of the nav, but the close tag is still existing, so please try to remove the close tag also to preserve the open closed tags as expected and to not make any conflict in the code 💯😊

2023-05-04 17:21 UTC, osamaashraf6 commented on index.html
> +          <nav><img src="images/Union.png" alt="Menu"></nav>
- [ ] Kindly 😃as stated by the previous reviewer it will be better to be consistent with the template, I recommend styling the header like the Figma Design and also using the correct font size and font weight for the logo.😊💯
- As you see here : 
- the Logo is not styled like the Figma Design , so it will be better if you follow the typography of the logo like the Figma Design 😊💯
- Also the hamburger icon 🚀 needs to place in the correct position to be like the Figma design and to make it nice for the users

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/236276396-6e89ee00-c7c4-4a8b-839f-34e5d92d65c1.png)   |    ![image](https://user-images.githubusercontent.com/83360636/236276191-f2c6528e-3965-4a03-a12d-17f39157baa1.png)  |

2023-05-04 17:21 UTC, osamaashraf6 commented on style.css
> +
- [ ] While you make a great effort 😃I see that you write here ```#body```, but in fact, the body does not have an id selector to make the style for it, so if for example at any element you want to give it style, it is necessary 🚀💯 to give it class or id selector after that you can call this element in the CSS file with ```.``` for the class or ```#``` with id and give it the style 👌
- Hint : 
- When you want to give the body style 💯😊it will be better if you call the body directly without class or id selector that's for best practice 
- As stated by the previous reviewer 😃kindly try to give the page ```margin: 0;```  to remove the default style, so it will be better if you follow the best practice for removing the default margin and padding from the page see below 😊⤵️

```snippet
*{
padding: 0;
margin: 0;
box-sizing: border-box;
 }

```

2023-05-05 12:56 UTC, tugsem requested changes
## Invalid Code Review Request ❌ 

Hi @MostafaBarodi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<h2>You have submitted a project, that fails with the linters setup Kindly add 's' after the ' workflow' and ensure you have the green tick: </h2>
![image](https://user-images.githubusercontent.com/91486791/236463345-a1a888aa-0244-4da3-9d77-87a952753e92.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-05 14:04 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @MostafaBarodi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 14:04 UTC, bobb-Rob commented on index.html
> +    </header>
- [ ] While you made efforts to re-do the toolbar/header section as advised by the previous reviewer, there is still work to be done in making sure it resembles the Figma design as much as possible. The left, top, and right paddings of the `header` element are not rightly done. First, I think you should add a height of about `70px` and remove the `padding-left: 24px;` and `padding-right: 24px;` on the `<header class="header-section container">`, then you ensure that the `left` and `right` space on the toolbar/header section is the same with the `left` and `right` space in the headline section. See the image below, and focus on the red markings.


![image](https://user-images.githubusercontent.com/84156714/236478439-31afec5b-5daa-49de-b59b-9ae13422f28e.png)

2023-05-05 21:37 UTC, usorfaitheloho requested changes
Hi @MostafaBarodi  :thumbsup:  ,

This is good to make it this far, keep it up, congratulations on the good work you have done so far.

There are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights
- Good use of JavaScript, HTML&CSS best practices ✔️ 
-  Well-structured files ✔️
<br/>
<br/>
<br/>

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 21:37 UTC, usorfaitheloho commented on index.html
> +         </div>
Great job implementing some of the suggestions by the previous, there's still some work to do to move to the next milestone but you're almost there 😄 . As suggested by the previous reviewer , you need to add the right padding and margin in the toolbar and headline section as the toolbar is too close to the border of the page and quite close to the headline section. Please implement the spacing so it looks close to the Figma design 👍 

Your design (take note of the red marker and please fix the errors there:

![image](https://user-images.githubusercontent.com/20537712/236571937-27151635-5cf2-4ada-8ef7-828c9049446f.png)

Figma template :

![image](https://user-images.githubusercontent.com/20537712/236572002-2f054045-ce9d-4d37-b17c-7a05de652ed3.png)

2023-05-05 21:37 UTC, usorfaitheloho commented on style.css
> +a:active { text-decoration: none; }
[Optional] Please try to fix the gap between the `Let's Connect` and the social icons to give you a good interface that suits users' preference 😄 , kindly correct it to be similar to the Figma design.

Your design:

![image](https://user-images.githubusercontent.com/20537712/236572657-7f1e2716-1e18-41e6-8982-66020947215a.png)'

Figma design:
![image](https://user-images.githubusercontent.com/20537712/236572758-9ecc5bcf-e7b0-47b9-8ada-574b00ece989.png)

2023-05-06 08:28 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @MostafaBarodi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- No Linters Error :100: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 08:28 UTC, GedeonTS commented on index.html
> +
- Please make sure to the logo and hamburger images are displaying well, and Kindly make sure to stick to the [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

**Figma Design**
![236572002-2f054045-ce9d-4d37-b17c-7a05de652ed3](https://user-images.githubusercontent.com/97834160/236612478-079a69fb-7d09-4b76-8618-03d3bfa274d9.png)

**You Design**
![Screenshot from 2023-05-06 10-12-37](https://user-images.githubusercontent.com/97834160/236612448-d227aa2f-1e95-47c4-a6c7-193be3e1c4af.png)

2023-05-06 08:28 UTC, GedeonTS commented on index.html
> +          <div id="bio" >
- Kindly make sure to align this greeting text according to the Figma Design. you can use `<br />` for example

**FIgma Design**
![Screenshot from 2023-05-06 10-25-31](https://user-images.githubusercontent.com/97834160/236612707-56d34c3b-41b7-4636-9692-7bc9c62e5c80.png)

**Your Design**
![Screenshot from 2023-05-06 10-12-37](https://user-images.githubusercontent.com/97834160/236612712-1440f769-59be-4a36-b8e3-0cbf561012e7.png)

- I think it would be better to use the appropriate font weight to stick to the Figma template according to [this requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md#:~:text=Your%20website%20should%20look%20exactly%20like%20the%20design%20(e.g.%20font%2C%20colors%2C%20images%2C%20text%2C%20margins)%20using%20the%20templates%20in%20Figma.)

2023-05-06 11:01 UTC, Johnadibe requested changes
# Status: Required Changes ♻️
### Hi @MostafaBarodi🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Your project is documented professionally✔️
- No linter errors ✔️

 ## Required Changes ♻️

> - [ ] If you think that there is something wrong with the provided reviews or you think that you still need to work on some changes requested by the previous CR. Please kindly request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 11:57 UTC, MostafaBarodi commented on styles.css
> +
done , please check again

2023-05-06 12:04 UTC, ABDULALI3468 approved these changes
Hi @MostafaBarodi , 👍 

# APPROVED 💯 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 
☑️Implemented changes asked by the previous CR.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 12:10 UTC, merged

2023-05-06 12:15 UTC, MostafaBarodi commented
can you approve please the first part of the project ,it appears incomplete
from my side in dashboard

On Sat, May 6, 2023 at 3:05 PM ABDUL ALI ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @MostafaBarodi <https://github.com/MostafaBarodi> , 👍
> APPROVED 💯 🥇
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/6fe04a1dc1a9ddf9fcb3b413921cb8316379073c9d3cd3f9fbf96f1bc6e1b65f/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a395a45324f6f397a52432f67697068792e676966>
> Highlights
>
> ☑️Implemented changes asked by the previous CR.
> ✅All linters are checked.
> ✅Project is professionally documented.
> ✅The right GitHub flow method has been used.
> ✅Professional pull request title and description.
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear, and please remember to tag me in your question so I can
> receive the notification.
>
>
>    - This is My *GitHub*: [image: GitHub followers]
>    <https://camo.githubusercontent.com/f5132a63c0aabcf4cac703fb7f3ac03fdfe86fd3676c3b4439e831950a833608/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f666f6c6c6f776572732f414244554c414c49333436383f6c6162656c3d414244554c414c49267374796c653d736f6369616c>
>    - This is My *Linkedin*: [image: Linkedin Badge]
>    <https://www.linkedin.com/in/abdul-ali-5400bb216/>
>    - This is My *Twitter*: [image: Twitter Badge]
>    <https://twitter.com/mrabdul_ali>
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MostafaBarodi/web-portfolio/pull/1#pullrequestreview-1415763954>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUMQBICZHE3DA3EU4MDXK63XEY47LANCNFSM6AAAAAAXUMAJ5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>